// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AgreementsController from "./agreements_controller"
application.register("agreements", AgreementsController)

import BatchCalculatorController from "./batch_calculator_controller"
application.register("batch-calculator", BatchCalculatorController)

import BatchController from "./batch_controller"
application.register("batch", BatchController)

import BenefitController from "./benefit_controller"
application.register("benefit", BenefitController)

import CheckboxSelectAllController from "./checkbox_select_all_controller"
application.register("checkbox-select-all", CheckboxSelectAllController)

import CoopController from "./coop_controller"
application.register("coop", CoopController)

import DigitOnlyController from "./digit_only_controller"
application.register("digit-only", DigitOnlyController)

import DynamicGraphController from "./dynamic_graph_controller"
application.register("dynamic-graph", DynamicGraphController)

import Flatpickr2Controller from "./flatpickr2_controller"
application.register("flatpickr2", Flatpickr2Controller)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GeographyController from "./geography_controller"
application.register("geography", GeographyController)

import GraphController from "./graph_controller"
application.register("graph", GraphController)

import GroupPlanController from "./group_plan_controller"
application.register("group-plan", GroupPlanController)

import LoanFormController from "./loan_form_controller"
application.register("loan-form", LoanFormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import NumberFormatterController from "./number_formatter_controller"
application.register("number-formatter", NumberFormatterController)

import ParentController from "./parent_controller"
application.register("parent", ParentController)

import PasswordStrengthController from "./password_strength_controller"
application.register("password-strength", PasswordStrengthController)

import PaymentUploadController from "./payment_upload_controller"
application.register("payment-upload", PaymentUploadController)

import PlanAgreeController from "./plan_agree_controller"
application.register("plan-agree", PlanAgreeController)

import ProgressBarController from "./progress_bar_controller"
application.register("progress-bar", ProgressBarController)

import QuestionaireController from "./questionaire_controller"
application.register("questionaire", QuestionaireController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import RetainCheckController from "./retain_check_controller"
application.register("retain-check", RetainCheckController)

import SelectMultipleController from "./select_multiple_controller"
application.register("select-multiple", SelectMultipleController)

import ShowMembersController from "./show_members_controller"
application.register("show-members", ShowMembersController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)

import TogglerController from "./toggler_controller"
application.register("toggler", TogglerController)

import Ts__SelectController from "./ts/select_controller"
application.register("ts--select", Ts__SelectController)

import ViewBenefitsController from "./view_benefits_controller"
application.register("view-benefits", ViewBenefitsController)
