:scheduler:
  :schedule:
    group_remit_update:
      cron: '33 13 * * *' # Set the desired time for the job to run (6:00 am in this example)
      class: 'GroupRemitStatusUpdater'
      queue: 'default'
    batch_status_update:
      cron: '25 13 * * *' 
      class: 'LoanStatusUpdater'
      queue: 'default'
    payment_reminder:
      cron: '33 13 * * *'
      class: 'GroupRemitPaymentStatusUpdater'
      queue: 'default'

