:concurrency: 5
:scheduler:
  :schedule:
    group_remit_update:
      cron: '59 23 * * *' # Set the desired time for the job to run 
      class: 'GroupRemitStatusUpdater'
      queue: 'default'
    batch_status_update:
      cron: '59 23 * * *' 
      class: 'LoanStatusUpdater'
      queue: 'default'
    payment_reminder:
      cron: '59 23 * * *'
      class: 'GroupRemitPaymentStatusUpdater'
      queue: 'default'

