:scheduler:
  :schedule:
    group_remit_update:
      cron: '0 6 * * *' # Set the desired time for the job to run (6:00 am in this example)
      class: 'GroupRemitStatusUpdater'
      queue: 'default'
    batch_status_update:
      cron: '16 9 * * *' 
      class: 'LoanStatusUpdater'
      queue: 'default'
