require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/loan_insurance/batch_remits", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # LoanInsurance::BatchRemit. As you add validations to LoanInsurance::BatchRemit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LoanInsurance::BatchRemit.create! valid_attributes
      get loan_insurance_batch_remits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      batch_remit = LoanInsurance::BatchRemit.create! valid_attributes
      get loan_insurance_batch_remit_url(batch_remit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_loan_insurance_batch_remit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      batch_remit = LoanInsurance::BatchRemit.create! valid_attributes
      get edit_loan_insurance_batch_remit_url(batch_remit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LoanInsurance::BatchRemit" do
        expect {
          post loan_insurance_batch_remits_url, params: { loan_insurance_batch_remit: valid_attributes }
        }.to change(LoanInsurance::BatchRemit, :count).by(1)
      end

      it "redirects to the created loan_insurance_batch_remit" do
        post loan_insurance_batch_remits_url, params: { loan_insurance_batch_remit: valid_attributes }
        expect(response).to redirect_to(loan_insurance_batch_remit_url(LoanInsurance::BatchRemit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LoanInsurance::BatchRemit" do
        expect {
          post loan_insurance_batch_remits_url, params: { loan_insurance_batch_remit: invalid_attributes }
        }.to change(LoanInsurance::BatchRemit, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post loan_insurance_batch_remits_url, params: { loan_insurance_batch_remit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested loan_insurance_batch_remit" do
        batch_remit = LoanInsurance::BatchRemit.create! valid_attributes
        patch loan_insurance_batch_remit_url(batch_remit), params: { loan_insurance_batch_remit: new_attributes }
        batch_remit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the loan_insurance_batch_remit" do
        batch_remit = LoanInsurance::BatchRemit.create! valid_attributes
        patch loan_insurance_batch_remit_url(batch_remit), params: { loan_insurance_batch_remit: new_attributes }
        batch_remit.reload
        expect(response).to redirect_to(loan_insurance_batch_remit_url(batch_remit))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        batch_remit = LoanInsurance::BatchRemit.create! valid_attributes
        patch loan_insurance_batch_remit_url(batch_remit), params: { loan_insurance_batch_remit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested loan_insurance_batch_remit" do
      batch_remit = LoanInsurance::BatchRemit.create! valid_attributes
      expect {
        delete loan_insurance_batch_remit_url(batch_remit)
      }.to change(LoanInsurance::BatchRemit, :count).by(-1)
    end

    it "redirects to the loan_insurance_batch_remits list" do
      batch_remit = LoanInsurance::BatchRemit.create! valid_attributes
      delete loan_insurance_batch_remit_url(batch_remit)
      expect(response).to redirect_to(loan_insurance_batch_remits_url)
    end
  end
end
